import fs from "node:fs/promises";

const baseDir = new URL("../", import.meta.url);
const sourceUrl = new URL("選手スプレッドシート/01_現役選手300名.csv", baseDir);
const outputUrl = new URL("data/rider_roster.js", baseDir);
const statFields = [
  "sprint", "acceleration", "punch", "cruise", "climb", "stamina", "resistance",
  "technique", "bikeControl", "pave", "recovery", "dailyRecovery", "teamwork", "ego", "fighting",
];

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    if (quoted) {
      if (char === '"' && text[index + 1] === '"') {
        field += '"';
        index += 1;
      } else if (char === '"') {
        quoted = false;
      } else {
        field += char;
      }
    } else if (char === '"') {
      quoted = true;
    } else if (char === ",") {
      row.push(field);
      field = "";
    } else if (char === "\n") {
      row.push(field.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      field = "";
    } else {
      field += char;
    }
  }
  if (field || row.length) {
    row.push(field.replace(/\r$/, ""));
    rows.push(row);
  }
  return rows;
}

const rows = parseCsv(await fs.readFile(sourceUrl, "utf8"));
const headers = rows.shift().map((header) => header.replace(/^\uFEFF/, ""));
const records = rows
  .filter((row) => row.some((value) => value !== ""))
  .map((row) => Object.fromEntries(headers.map((header, index) => [header, row[index] ?? ""])));

const splitList = (value) => String(value || "").split("/").map((item) => item.trim()).filter(Boolean);
const toNumber = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;

const roster = records.map((row) => ({
  id: `rider_${row.no}`,
  name: row.name,
  riderTitle: row.rider_title || "",
  country: row.country,
  era: row.era,
  motif: row.name,
  primaryArchetype: row.primary_archetype,
  secondaryArchetype: row.secondary_archetype,
  aptitudeTags: splitList(row.aptitude_tags),
  aceAptitude: toNumber(row.ace_aptitude),
  supportAptitude: toNumber(row.support_aptitude),
  preferredRoles: splitList(row.preferred_roles),
  creditSalary: toNumber(row.credit_salary),
  paveBasis: row.pave_basis || "",
  stats: Object.fromEntries(statFields.map((field) => [field, toNumber(row[field], 50)])),
}));

if (roster.length !== 300) throw new Error(`Expected 300 riders, received ${roster.length}`);
if (new Set(roster.map((rider) => rider.id)).size !== roster.length) throw new Error("Duplicate rider ids");
if (new Set(roster.map((rider) => rider.name)).size !== roster.length) throw new Error("Duplicate rider names");

const output = `// Generated by tools/build_browser_rider_roster.mjs. Do not edit by hand.\nwindow.RIDER_ROSTER = ${JSON.stringify(roster, null, 2)};\n`;
await fs.writeFile(outputUrl, output, "utf8");
console.log(`Wrote ${roster.length} browser riders`);
