import fs from "node:fs/promises";

const baseDir = new URL("../", import.meta.url);
const readJson = async (path) => JSON.parse(await fs.readFile(new URL(path, baseDir), "utf8"));
const assignments = await readJson("data/rider_card_assignments.json");
const activeAssignments = assignments.filter((entry) =>
  entry.rosterFile.replaceAll("\\", "/").endsWith("選手スプレッドシート/01_現役選手300名.csv"));
const sourceFiles = [
  "data/basic_card_templates.json", "data/specialty_card_templates.json",
  "data/assist_card_role_templates.json", "data/generic_decisive_card_templates.json",
  "data/ace_signature_cards.json", "data/elite_assist_cards.json",
];
const payloads = await Promise.all(sourceFiles.map(async (path) => ({ path, entries: await readJson(path) })));
const byIdSlot = new Map();
const byNameSlot = new Map();

function register(card) {
  if (!card?.name || !card.slot) return;
  if (card.id) byIdSlot.set(`${card.id}:${card.slot}`, card);
  if (!byNameSlot.has(`${card.name}:${card.slot}`)) byNameSlot.set(`${card.name}:${card.slot}`, card);
}

for (const { path, entries } of payloads) {
  if (path.endsWith("elite_assist_cards.json")) entries.forEach((entry) => (entry.cards || []).forEach(register));
  else entries.forEach(register);
}

function resolve(card) {
  const slot = Number(card.cost) === 1 ? "basic" : Number(card.cost) === 2 ? "specialty" : "decisive";
  const definition = (card.id && byIdSlot.get(`${card.id}:${slot}`)) || byNameSlot.get(`${card.name}:${slot}`) || {};
  return {
    id: card.id || definition.id || `${slot}-${card.name}`,
    name: card.name, slot, cost: Number(card.cost || definition.cost),
    target: card.target || definition.target || "本人",
    description: definition.description || card.description || card.name,
    terrainId: definition.terrainId || null, abilities: definition.abilities || [],
    usageLimit: definition.usageLimit ?? (slot === "decisive" ? 1 : null),
    assignmentScore: Number(card.score || 70),
  };
}

const catalog = Object.fromEntries(activeAssignments.map((assignment) => {
  const riderName = assignment.riderName;
  const cards = [...assignment.basicCards, ...assignment.specialtyCards, assignment.decisiveCard].map(resolve);
  if (cards.length !== 6) throw new Error(`Expected six cards: ${riderName}`);
  return [riderName, { roleType: assignment.roleType, assignmentBasis: assignment.assignmentBasis, cards }];
}));

const output = `// Generated by tools/build_browser_card_catalog.mjs. Do not edit by hand.\nwindow.RIDER_CARD_CATALOG = ${JSON.stringify(catalog, null, 2)};\n`;
await fs.writeFile(new URL("data/rider_card_catalog.js", baseDir), output, "utf8");
console.log(`Wrote ${Object.keys(catalog).length} riders / ${Object.values(catalog).reduce((sum, rider) => sum + rider.cards.length, 0)} cards`);
